language: node_js
node_js:
  - "4.1"
sudo: false
branches:
  only:
    - master
install:
- npm install
script:
- npm run clean:build
after_success:
- bash ./travis-deploy.sh
env:
  global:
    - GITHUB_REPO: "optimizely/developers.optimizely.com"
    - secure: "jB5YKTJARmPjTmjYrrYMwY74pVuEX6KMeyzHkEyWvMyvQiB6/keO3sEKb+E3N+ZyzUQg9upqnyqxE4uTA4G2R0xnCUWEDRWQ/qA/wvG4a7JiElRKPk7lEhsy0IIa2TNdZKMhf3MJUf9/fh4rpM4pp+D5u3w27GQT6m5EpWe+vPEAmDgwq47yAW0jQtvzYFCwuMV3YNBDkkUCL5Hw3A9UTm+ntwjH+LJJvkp3hFvgMDQXXwC/CkL5ivnR18YBS3hNg5U7aQfJRmZYis9Ng7wDK108oSDJMh8NySYGUGOQMNwZfBqKSTF4OR0GZrrC9JPLIs8oF01Ut0Jtqe8HgcX9/v02kEFspkfNAPWwyl9SQNRcEy6x239ACGeVOXjmGGlJsB4Eyu39Tqa2jojLgJCNHkMfG7BK74Eg5B0FePpSguzb1YjIYM8dXEjhQFx4Te4LoPtsh5AmbRe1Xe7vlWGDNRfQLDYvNpZ4EErHjeHI1wsZB9xYCF8iPDn8LW1uvnGbnbWvumorUxmyK79el55/4a1V22RYhQ5RfG+dODk659hndkx9dTaDJixrLypAdCseEIl5HwT/pmuRbWKRd6C1MLxG+PZFiNrSdC3LjcMoxluVeMteZ7nLCIBNLjXASYJRckF5+vVN0xbTh1WxsyKva/v62RnHbU6SMMIkwue5S3Q="
